// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: craq/v1/transport.proto

package grpcproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoordinatorService_Bootstrap_FullMethodName            = "/craq.v1.CoordinatorService/Bootstrap"
	CoordinatorService_RegisterNode_FullMethodName         = "/craq.v1.CoordinatorService/RegisterNode"
	CoordinatorService_AddNode_FullMethodName              = "/craq.v1.CoordinatorService/AddNode"
	CoordinatorService_BeginDrainNode_FullMethodName       = "/craq.v1.CoordinatorService/BeginDrainNode"
	CoordinatorService_MarkNodeDead_FullMethodName         = "/craq.v1.CoordinatorService/MarkNodeDead"
	CoordinatorService_RoutingSnapshot_FullMethodName      = "/craq.v1.CoordinatorService/RoutingSnapshot"
	CoordinatorService_ReportReplicaReady_FullMethodName   = "/craq.v1.CoordinatorService/ReportReplicaReady"
	CoordinatorService_ReportReplicaRemoved_FullMethodName = "/craq.v1.CoordinatorService/ReportReplicaRemoved"
	CoordinatorService_ReportNodeHeartbeat_FullMethodName  = "/craq.v1.CoordinatorService/ReportNodeHeartbeat"
	CoordinatorService_ReportNodeRecovered_FullMethodName  = "/craq.v1.CoordinatorService/ReportNodeRecovered"
	CoordinatorService_EvaluateLiveness_FullMethodName     = "/craq.v1.CoordinatorService/EvaluateLiveness"
)

// CoordinatorServiceClient is the client API for CoordinatorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoordinatorServiceClient interface {
	Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*ServerState, error)
	RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*ServerState, error)
	AddNode(ctx context.Context, in *MembershipMutationRequest, opts ...grpc.CallOption) (*ServerState, error)
	BeginDrainNode(ctx context.Context, in *MembershipMutationRequest, opts ...grpc.CallOption) (*ServerState, error)
	MarkNodeDead(ctx context.Context, in *MembershipMutationRequest, opts ...grpc.CallOption) (*ServerState, error)
	RoutingSnapshot(ctx context.Context, in *RoutingSnapshotRequest, opts ...grpc.CallOption) (*RoutingSnapshotResponse, error)
	ReportReplicaReady(ctx context.Context, in *ReplicaReadyReport, opts ...grpc.CallOption) (*ServerState, error)
	ReportReplicaRemoved(ctx context.Context, in *ReplicaRemovedReport, opts ...grpc.CallOption) (*ServerState, error)
	ReportNodeHeartbeat(ctx context.Context, in *NodeStatus, opts ...grpc.CallOption) (*Empty, error)
	ReportNodeRecovered(ctx context.Context, in *NodeRecoveryReport, opts ...grpc.CallOption) (*Empty, error)
	EvaluateLiveness(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerState, error)
}

type coordinatorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCoordinatorServiceClient(cc grpc.ClientConnInterface) CoordinatorServiceClient {
	return &coordinatorServiceClient{cc}
}

func (c *coordinatorServiceClient) Bootstrap(ctx context.Context, in *BootstrapRequest, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_Bootstrap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RegisterNode(ctx context.Context, in *RegisterNodeRequest, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_RegisterNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) AddNode(ctx context.Context, in *MembershipMutationRequest, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_AddNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) BeginDrainNode(ctx context.Context, in *MembershipMutationRequest, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_BeginDrainNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) MarkNodeDead(ctx context.Context, in *MembershipMutationRequest, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_MarkNodeDead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) RoutingSnapshot(ctx context.Context, in *RoutingSnapshotRequest, opts ...grpc.CallOption) (*RoutingSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RoutingSnapshotResponse)
	err := c.cc.Invoke(ctx, CoordinatorService_RoutingSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReportReplicaReady(ctx context.Context, in *ReplicaReadyReport, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_ReportReplicaReady_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReportReplicaRemoved(ctx context.Context, in *ReplicaRemovedReport, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_ReportReplicaRemoved_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReportNodeHeartbeat(ctx context.Context, in *NodeStatus, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoordinatorService_ReportNodeHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) ReportNodeRecovered(ctx context.Context, in *NodeRecoveryReport, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, CoordinatorService_ReportNodeRecovered_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coordinatorServiceClient) EvaluateLiveness(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*ServerState, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ServerState)
	err := c.cc.Invoke(ctx, CoordinatorService_EvaluateLiveness_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoordinatorServiceServer is the server API for CoordinatorService service.
// All implementations must embed UnimplementedCoordinatorServiceServer
// for forward compatibility.
type CoordinatorServiceServer interface {
	Bootstrap(context.Context, *BootstrapRequest) (*ServerState, error)
	RegisterNode(context.Context, *RegisterNodeRequest) (*ServerState, error)
	AddNode(context.Context, *MembershipMutationRequest) (*ServerState, error)
	BeginDrainNode(context.Context, *MembershipMutationRequest) (*ServerState, error)
	MarkNodeDead(context.Context, *MembershipMutationRequest) (*ServerState, error)
	RoutingSnapshot(context.Context, *RoutingSnapshotRequest) (*RoutingSnapshotResponse, error)
	ReportReplicaReady(context.Context, *ReplicaReadyReport) (*ServerState, error)
	ReportReplicaRemoved(context.Context, *ReplicaRemovedReport) (*ServerState, error)
	ReportNodeHeartbeat(context.Context, *NodeStatus) (*Empty, error)
	ReportNodeRecovered(context.Context, *NodeRecoveryReport) (*Empty, error)
	EvaluateLiveness(context.Context, *Empty) (*ServerState, error)
	mustEmbedUnimplementedCoordinatorServiceServer()
}

// UnimplementedCoordinatorServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoordinatorServiceServer struct{}

func (UnimplementedCoordinatorServiceServer) Bootstrap(context.Context, *BootstrapRequest) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method Bootstrap not implemented")
}
func (UnimplementedCoordinatorServiceServer) RegisterNode(context.Context, *RegisterNodeRequest) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) AddNode(context.Context, *MembershipMutationRequest) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method AddNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) BeginDrainNode(context.Context, *MembershipMutationRequest) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method BeginDrainNode not implemented")
}
func (UnimplementedCoordinatorServiceServer) MarkNodeDead(context.Context, *MembershipMutationRequest) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkNodeDead not implemented")
}
func (UnimplementedCoordinatorServiceServer) RoutingSnapshot(context.Context, *RoutingSnapshotRequest) (*RoutingSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RoutingSnapshot not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReportReplicaReady(context.Context, *ReplicaReadyReport) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportReplicaReady not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReportReplicaRemoved(context.Context, *ReplicaRemovedReport) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportReplicaRemoved not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReportNodeHeartbeat(context.Context, *NodeStatus) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportNodeHeartbeat not implemented")
}
func (UnimplementedCoordinatorServiceServer) ReportNodeRecovered(context.Context, *NodeRecoveryReport) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportNodeRecovered not implemented")
}
func (UnimplementedCoordinatorServiceServer) EvaluateLiveness(context.Context, *Empty) (*ServerState, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateLiveness not implemented")
}
func (UnimplementedCoordinatorServiceServer) mustEmbedUnimplementedCoordinatorServiceServer() {}
func (UnimplementedCoordinatorServiceServer) testEmbeddedByValue()                            {}

// UnsafeCoordinatorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoordinatorServiceServer will
// result in compilation errors.
type UnsafeCoordinatorServiceServer interface {
	mustEmbedUnimplementedCoordinatorServiceServer()
}

func RegisterCoordinatorServiceServer(s grpc.ServiceRegistrar, srv CoordinatorServiceServer) {
	// If the following call panics, it indicates UnimplementedCoordinatorServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoordinatorService_ServiceDesc, srv)
}

func _CoordinatorService_Bootstrap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).Bootstrap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_Bootstrap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).Bootstrap(ctx, req.(*BootstrapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RegisterNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RegisterNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RegisterNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RegisterNode(ctx, req.(*RegisterNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_AddNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).AddNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_AddNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).AddNode(ctx, req.(*MembershipMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_BeginDrainNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).BeginDrainNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_BeginDrainNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).BeginDrainNode(ctx, req.(*MembershipMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_MarkNodeDead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MembershipMutationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).MarkNodeDead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_MarkNodeDead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).MarkNodeDead(ctx, req.(*MembershipMutationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_RoutingSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RoutingSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).RoutingSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_RoutingSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).RoutingSnapshot(ctx, req.(*RoutingSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReportReplicaReady_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaReadyReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReportReplicaReady(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReportReplicaReady_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReportReplicaReady(ctx, req.(*ReplicaReadyReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReportReplicaRemoved_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplicaRemovedReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReportReplicaRemoved(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReportReplicaRemoved_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReportReplicaRemoved(ctx, req.(*ReplicaRemovedReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReportNodeHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeStatus)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReportNodeHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReportNodeHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReportNodeHeartbeat(ctx, req.(*NodeStatus))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_ReportNodeRecovered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeRecoveryReport)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).ReportNodeRecovered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_ReportNodeRecovered_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).ReportNodeRecovered(ctx, req.(*NodeRecoveryReport))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoordinatorService_EvaluateLiveness_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoordinatorServiceServer).EvaluateLiveness(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoordinatorService_EvaluateLiveness_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoordinatorServiceServer).EvaluateLiveness(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// CoordinatorService_ServiceDesc is the grpc.ServiceDesc for CoordinatorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoordinatorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "craq.v1.CoordinatorService",
	HandlerType: (*CoordinatorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Bootstrap",
			Handler:    _CoordinatorService_Bootstrap_Handler,
		},
		{
			MethodName: "RegisterNode",
			Handler:    _CoordinatorService_RegisterNode_Handler,
		},
		{
			MethodName: "AddNode",
			Handler:    _CoordinatorService_AddNode_Handler,
		},
		{
			MethodName: "BeginDrainNode",
			Handler:    _CoordinatorService_BeginDrainNode_Handler,
		},
		{
			MethodName: "MarkNodeDead",
			Handler:    _CoordinatorService_MarkNodeDead_Handler,
		},
		{
			MethodName: "RoutingSnapshot",
			Handler:    _CoordinatorService_RoutingSnapshot_Handler,
		},
		{
			MethodName: "ReportReplicaReady",
			Handler:    _CoordinatorService_ReportReplicaReady_Handler,
		},
		{
			MethodName: "ReportReplicaRemoved",
			Handler:    _CoordinatorService_ReportReplicaRemoved_Handler,
		},
		{
			MethodName: "ReportNodeHeartbeat",
			Handler:    _CoordinatorService_ReportNodeHeartbeat_Handler,
		},
		{
			MethodName: "ReportNodeRecovered",
			Handler:    _CoordinatorService_ReportNodeRecovered_Handler,
		},
		{
			MethodName: "EvaluateLiveness",
			Handler:    _CoordinatorService_EvaluateLiveness_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "craq/v1/transport.proto",
}

const (
	StorageService_Get_FullMethodName                    = "/craq.v1.StorageService/Get"
	StorageService_Put_FullMethodName                    = "/craq.v1.StorageService/Put"
	StorageService_Delete_FullMethodName                 = "/craq.v1.StorageService/Delete"
	StorageService_AddReplicaAsTail_FullMethodName       = "/craq.v1.StorageService/AddReplicaAsTail"
	StorageService_ActivateReplica_FullMethodName        = "/craq.v1.StorageService/ActivateReplica"
	StorageService_MarkReplicaLeaving_FullMethodName     = "/craq.v1.StorageService/MarkReplicaLeaving"
	StorageService_RemoveReplica_FullMethodName          = "/craq.v1.StorageService/RemoveReplica"
	StorageService_UpdateChainPeers_FullMethodName       = "/craq.v1.StorageService/UpdateChainPeers"
	StorageService_ResumeRecoveredReplica_FullMethodName = "/craq.v1.StorageService/ResumeRecoveredReplica"
	StorageService_RecoverReplica_FullMethodName         = "/craq.v1.StorageService/RecoverReplica"
	StorageService_DropRecoveredReplica_FullMethodName   = "/craq.v1.StorageService/DropRecoveredReplica"
	StorageService_ForwardWrite_FullMethodName           = "/craq.v1.StorageService/ForwardWrite"
	StorageService_CommitWrite_FullMethodName            = "/craq.v1.StorageService/CommitWrite"
	StorageService_Replicate_FullMethodName              = "/craq.v1.StorageService/Replicate"
	StorageService_FetchSnapshot_FullMethodName          = "/craq.v1.StorageService/FetchSnapshot"
	StorageService_FetchCommittedSequence_FullMethodName = "/craq.v1.StorageService/FetchCommittedSequence"
)

// StorageServiceClient is the client API for StorageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageServiceClient interface {
	Get(ctx context.Context, in *ClientGetRequest, opts ...grpc.CallOption) (*ReadResult, error)
	Put(ctx context.Context, in *ClientPutRequest, opts ...grpc.CallOption) (*CommitResult, error)
	Delete(ctx context.Context, in *ClientDeleteRequest, opts ...grpc.CallOption) (*CommitResult, error)
	AddReplicaAsTail(ctx context.Context, in *AddReplicaAsTailCommand, opts ...grpc.CallOption) (*Empty, error)
	ActivateReplica(ctx context.Context, in *ActivateReplicaCommand, opts ...grpc.CallOption) (*Empty, error)
	MarkReplicaLeaving(ctx context.Context, in *MarkReplicaLeavingCommand, opts ...grpc.CallOption) (*Empty, error)
	RemoveReplica(ctx context.Context, in *RemoveReplicaCommand, opts ...grpc.CallOption) (*Empty, error)
	UpdateChainPeers(ctx context.Context, in *UpdateChainPeersCommand, opts ...grpc.CallOption) (*Empty, error)
	ResumeRecoveredReplica(ctx context.Context, in *ResumeRecoveredReplicaCommand, opts ...grpc.CallOption) (*Empty, error)
	RecoverReplica(ctx context.Context, in *RecoverReplicaCommand, opts ...grpc.CallOption) (*Empty, error)
	DropRecoveredReplica(ctx context.Context, in *DropRecoveredReplicaCommand, opts ...grpc.CallOption) (*Empty, error)
	ForwardWrite(ctx context.Context, in *ForwardWriteRequest, opts ...grpc.CallOption) (*Empty, error)
	CommitWrite(ctx context.Context, in *CommitWriteRequest, opts ...grpc.CallOption) (*Empty, error)
	Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicationFrame, ReplicationFrame], error)
	FetchSnapshot(ctx context.Context, in *FetchSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotEntry], error)
	FetchCommittedSequence(ctx context.Context, in *FetchCommittedSequenceRequest, opts ...grpc.CallOption) (*FetchCommittedSequenceResponse, error)
}

type storageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageServiceClient(cc grpc.ClientConnInterface) StorageServiceClient {
	return &storageServiceClient{cc}
}

func (c *storageServiceClient) Get(ctx context.Context, in *ClientGetRequest, opts ...grpc.CallOption) (*ReadResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadResult)
	err := c.cc.Invoke(ctx, StorageService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Put(ctx context.Context, in *ClientPutRequest, opts ...grpc.CallOption) (*CommitResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResult)
	err := c.cc.Invoke(ctx, StorageService_Put_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Delete(ctx context.Context, in *ClientDeleteRequest, opts ...grpc.CallOption) (*CommitResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitResult)
	err := c.cc.Invoke(ctx, StorageService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) AddReplicaAsTail(ctx context.Context, in *AddReplicaAsTailCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_AddReplicaAsTail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ActivateReplica(ctx context.Context, in *ActivateReplicaCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_ActivateReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) MarkReplicaLeaving(ctx context.Context, in *MarkReplicaLeavingCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_MarkReplicaLeaving_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RemoveReplica(ctx context.Context, in *RemoveReplicaCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_RemoveReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) UpdateChainPeers(ctx context.Context, in *UpdateChainPeersCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_UpdateChainPeers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ResumeRecoveredReplica(ctx context.Context, in *ResumeRecoveredReplicaCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_ResumeRecoveredReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) RecoverReplica(ctx context.Context, in *RecoverReplicaCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_RecoverReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) DropRecoveredReplica(ctx context.Context, in *DropRecoveredReplicaCommand, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_DropRecoveredReplica_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) ForwardWrite(ctx context.Context, in *ForwardWriteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_ForwardWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) CommitWrite(ctx context.Context, in *CommitWriteRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, StorageService_CommitWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageServiceClient) Replicate(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[ReplicationFrame, ReplicationFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[0], StorageService_Replicate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReplicationFrame, ReplicationFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReplicateClient = grpc.BidiStreamingClient[ReplicationFrame, ReplicationFrame]

func (c *storageServiceClient) FetchSnapshot(ctx context.Context, in *FetchSnapshotRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SnapshotEntry], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageService_ServiceDesc.Streams[1], StorageService_FetchSnapshot_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchSnapshotRequest, SnapshotEntry]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_FetchSnapshotClient = grpc.ServerStreamingClient[SnapshotEntry]

func (c *storageServiceClient) FetchCommittedSequence(ctx context.Context, in *FetchCommittedSequenceRequest, opts ...grpc.CallOption) (*FetchCommittedSequenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchCommittedSequenceResponse)
	err := c.cc.Invoke(ctx, StorageService_FetchCommittedSequence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageServiceServer is the server API for StorageService service.
// All implementations must embed UnimplementedStorageServiceServer
// for forward compatibility.
type StorageServiceServer interface {
	Get(context.Context, *ClientGetRequest) (*ReadResult, error)
	Put(context.Context, *ClientPutRequest) (*CommitResult, error)
	Delete(context.Context, *ClientDeleteRequest) (*CommitResult, error)
	AddReplicaAsTail(context.Context, *AddReplicaAsTailCommand) (*Empty, error)
	ActivateReplica(context.Context, *ActivateReplicaCommand) (*Empty, error)
	MarkReplicaLeaving(context.Context, *MarkReplicaLeavingCommand) (*Empty, error)
	RemoveReplica(context.Context, *RemoveReplicaCommand) (*Empty, error)
	UpdateChainPeers(context.Context, *UpdateChainPeersCommand) (*Empty, error)
	ResumeRecoveredReplica(context.Context, *ResumeRecoveredReplicaCommand) (*Empty, error)
	RecoverReplica(context.Context, *RecoverReplicaCommand) (*Empty, error)
	DropRecoveredReplica(context.Context, *DropRecoveredReplicaCommand) (*Empty, error)
	ForwardWrite(context.Context, *ForwardWriteRequest) (*Empty, error)
	CommitWrite(context.Context, *CommitWriteRequest) (*Empty, error)
	Replicate(grpc.BidiStreamingServer[ReplicationFrame, ReplicationFrame]) error
	FetchSnapshot(*FetchSnapshotRequest, grpc.ServerStreamingServer[SnapshotEntry]) error
	FetchCommittedSequence(context.Context, *FetchCommittedSequenceRequest) (*FetchCommittedSequenceResponse, error)
	mustEmbedUnimplementedStorageServiceServer()
}

// UnimplementedStorageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageServiceServer struct{}

func (UnimplementedStorageServiceServer) Get(context.Context, *ClientGetRequest) (*ReadResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedStorageServiceServer) Put(context.Context, *ClientPutRequest) (*CommitResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Put not implemented")
}
func (UnimplementedStorageServiceServer) Delete(context.Context, *ClientDeleteRequest) (*CommitResult, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedStorageServiceServer) AddReplicaAsTail(context.Context, *AddReplicaAsTailCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AddReplicaAsTail not implemented")
}
func (UnimplementedStorageServiceServer) ActivateReplica(context.Context, *ActivateReplicaCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ActivateReplica not implemented")
}
func (UnimplementedStorageServiceServer) MarkReplicaLeaving(context.Context, *MarkReplicaLeavingCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method MarkReplicaLeaving not implemented")
}
func (UnimplementedStorageServiceServer) RemoveReplica(context.Context, *RemoveReplicaCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveReplica not implemented")
}
func (UnimplementedStorageServiceServer) UpdateChainPeers(context.Context, *UpdateChainPeersCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateChainPeers not implemented")
}
func (UnimplementedStorageServiceServer) ResumeRecoveredReplica(context.Context, *ResumeRecoveredReplicaCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ResumeRecoveredReplica not implemented")
}
func (UnimplementedStorageServiceServer) RecoverReplica(context.Context, *RecoverReplicaCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RecoverReplica not implemented")
}
func (UnimplementedStorageServiceServer) DropRecoveredReplica(context.Context, *DropRecoveredReplicaCommand) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DropRecoveredReplica not implemented")
}
func (UnimplementedStorageServiceServer) ForwardWrite(context.Context, *ForwardWriteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ForwardWrite not implemented")
}
func (UnimplementedStorageServiceServer) CommitWrite(context.Context, *CommitWriteRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method CommitWrite not implemented")
}
func (UnimplementedStorageServiceServer) Replicate(grpc.BidiStreamingServer[ReplicationFrame, ReplicationFrame]) error {
	return status.Error(codes.Unimplemented, "method Replicate not implemented")
}
func (UnimplementedStorageServiceServer) FetchSnapshot(*FetchSnapshotRequest, grpc.ServerStreamingServer[SnapshotEntry]) error {
	return status.Error(codes.Unimplemented, "method FetchSnapshot not implemented")
}
func (UnimplementedStorageServiceServer) FetchCommittedSequence(context.Context, *FetchCommittedSequenceRequest) (*FetchCommittedSequenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchCommittedSequence not implemented")
}
func (UnimplementedStorageServiceServer) mustEmbedUnimplementedStorageServiceServer() {}
func (UnimplementedStorageServiceServer) testEmbeddedByValue()                        {}

// UnsafeStorageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageServiceServer will
// result in compilation errors.
type UnsafeStorageServiceServer interface {
	mustEmbedUnimplementedStorageServiceServer()
}

func RegisterStorageServiceServer(s grpc.ServiceRegistrar, srv StorageServiceServer) {
	// If the following call panics, it indicates UnimplementedStorageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageService_ServiceDesc, srv)
}

func _StorageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Get(ctx, req.(*ClientGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientPutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Put_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Put(ctx, req.(*ClientPutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClientDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).Delete(ctx, req.(*ClientDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_AddReplicaAsTail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddReplicaAsTailCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).AddReplicaAsTail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_AddReplicaAsTail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).AddReplicaAsTail(ctx, req.(*AddReplicaAsTailCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ActivateReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ActivateReplicaCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ActivateReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ActivateReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ActivateReplica(ctx, req.(*ActivateReplicaCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_MarkReplicaLeaving_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkReplicaLeavingCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).MarkReplicaLeaving(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_MarkReplicaLeaving_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).MarkReplicaLeaving(ctx, req.(*MarkReplicaLeavingCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RemoveReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveReplicaCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RemoveReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RemoveReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RemoveReplica(ctx, req.(*RemoveReplicaCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_UpdateChainPeers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateChainPeersCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).UpdateChainPeers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_UpdateChainPeers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).UpdateChainPeers(ctx, req.(*UpdateChainPeersCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ResumeRecoveredReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResumeRecoveredReplicaCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ResumeRecoveredReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ResumeRecoveredReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ResumeRecoveredReplica(ctx, req.(*ResumeRecoveredReplicaCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_RecoverReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecoverReplicaCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).RecoverReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_RecoverReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).RecoverReplica(ctx, req.(*RecoverReplicaCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_DropRecoveredReplica_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropRecoveredReplicaCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).DropRecoveredReplica(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_DropRecoveredReplica_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).DropRecoveredReplica(ctx, req.(*DropRecoveredReplicaCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_ForwardWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ForwardWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).ForwardWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_ForwardWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).ForwardWrite(ctx, req.(*ForwardWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_CommitWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).CommitWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_CommitWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).CommitWrite(ctx, req.(*CommitWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageService_Replicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageServiceServer).Replicate(&grpc.GenericServerStream[ReplicationFrame, ReplicationFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_ReplicateServer = grpc.BidiStreamingServer[ReplicationFrame, ReplicationFrame]

func _StorageService_FetchSnapshot_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchSnapshotRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageServiceServer).FetchSnapshot(m, &grpc.GenericServerStream[FetchSnapshotRequest, SnapshotEntry]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageService_FetchSnapshotServer = grpc.ServerStreamingServer[SnapshotEntry]

func _StorageService_FetchCommittedSequence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchCommittedSequenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageServiceServer).FetchCommittedSequence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageService_FetchCommittedSequence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageServiceServer).FetchCommittedSequence(ctx, req.(*FetchCommittedSequenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageService_ServiceDesc is the grpc.ServiceDesc for StorageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "craq.v1.StorageService",
	HandlerType: (*StorageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _StorageService_Get_Handler,
		},
		{
			MethodName: "Put",
			Handler:    _StorageService_Put_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StorageService_Delete_Handler,
		},
		{
			MethodName: "AddReplicaAsTail",
			Handler:    _StorageService_AddReplicaAsTail_Handler,
		},
		{
			MethodName: "ActivateReplica",
			Handler:    _StorageService_ActivateReplica_Handler,
		},
		{
			MethodName: "MarkReplicaLeaving",
			Handler:    _StorageService_MarkReplicaLeaving_Handler,
		},
		{
			MethodName: "RemoveReplica",
			Handler:    _StorageService_RemoveReplica_Handler,
		},
		{
			MethodName: "UpdateChainPeers",
			Handler:    _StorageService_UpdateChainPeers_Handler,
		},
		{
			MethodName: "ResumeRecoveredReplica",
			Handler:    _StorageService_ResumeRecoveredReplica_Handler,
		},
		{
			MethodName: "RecoverReplica",
			Handler:    _StorageService_RecoverReplica_Handler,
		},
		{
			MethodName: "DropRecoveredReplica",
			Handler:    _StorageService_DropRecoveredReplica_Handler,
		},
		{
			MethodName: "ForwardWrite",
			Handler:    _StorageService_ForwardWrite_Handler,
		},
		{
			MethodName: "CommitWrite",
			Handler:    _StorageService_CommitWrite_Handler,
		},
		{
			MethodName: "FetchCommittedSequence",
			Handler:    _StorageService_FetchCommittedSequence_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Replicate",
			Handler:       _StorageService_Replicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchSnapshot",
			Handler:       _StorageService_FetchSnapshot_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "craq/v1/transport.proto",
}
